package com.i2p.accreditations.enums;

public enum Permission {
    // Accreditations
    VIEW_ACCREDITATION,
    CREATE_ACCREDITATION,
    EDIT_ACCREDITATION,
    DELETE_ACCREDITATION,

    // Chapters
    VIEW_CHAPTER,
    CREATE_CHAPTER,
    EDIT_CHAPTER,
    DELETE_CHAPTER,

    // Forms
    VIEW_FORM,
    CREATE_FORM,
    EDIT_FORM,
    DELETE_FORM,

    // Form Submissions
    VIEW_FORM_SUBMISSION,
    CREATE_FORM_SUBMISSION,
    EDIT_FORM_SUBMISSION,
    DELETE_FORM_SUBMISSION,

    // Checklists
    VIEW_CHECKLIST,
    CREATE_CHECKLIST,
    EDIT_CHECKLIST,
    DELETE_CHECKLIST,

    // Checklist Submissions
    VIEW_CHECKLIST_SUBMISSION,
    CREATE_CHECKLIST_SUBMISSION,
    EDIT_CHECKLIST_SUBMISSION,
    DELETE_CHECKLIST_SUBMISSION,

    // Policies
    VIEW_POLICY,
    CREATE_POLICY,
    EDIT_POLICY,
    DELETE_POLICY,

    // Policy Versions
    VIEW_POLICY_VERSION,
    CLONE_POLICY_VERSION,
    REVIEW_POLICY_VERSION,
    EDIT_POLICY_VERSION,
    DELETE_POLICY_VERSION
}
